import Header from "../../components/Header";
import Footer from "../../components/Footer";
import { site } from "../../lib/site";

export const metadata = {
  title: "Privacy Policy | WaseemRanker",
  description:
    "What data this site and this consultancy collect, why, how long it is kept, who it is shared with, and how to have it deleted.",
  alternates: { canonical: "/privacy" },
  robots: { index: true, follow: true },
};

function schema() {
  const url = `${site.url}/privacy`;
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${url}#page`,
        url,
        name: "Privacy Policy",
        isPartOf: { "@id": `${site.url}/#website` },
      },
      {
        "@type": "BreadcrumbList",
        "@id": `${url}#breadcrumb`,
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: site.url },
          { "@type": "ListItem", position: 2, name: "Privacy Policy", item: url },
        ],
      },
    ],
  };
}

export default function Privacy() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema()) }}
      />
      <Header />
      <main>
        <section className="hero hero-center">
          <div className="wrap">
            <h1>Privacy Policy</h1>
            <p className="lede">
              Plain English, no boilerplate padding. This explains what is collected, why,
              how long it is kept and how to have it removed.
            </p>
          </div>
        </section>

        <section>
          <div className="wrap" style={{ maxWidth: "820px" }}>
            <p>
              <strong>Last updated:</strong> September 2026. This policy covers{" "}
              {site.brand}, a local search consultancy operated by {site.name} from{" "}
              {site.countryName}, and the website you are reading it on.
            </p>

            <h2>Who is responsible for your data</h2>
            <p>
              {site.name}, trading as {site.brand}, is the data controller for any
              personal information described here. The contact point for every request,
              question or complaint about data is{" "}
              <a href={`mailto:${site.email}`}>{site.email}</a>.
            </p>

            <h2>What this website collects</h2>
            <p>
              This site does not have a contact form, a newsletter signup, a login area or
              an e-commerce checkout. It sets no advertising cookies and runs no
              cross-site tracking pixels. The buttons on the site open your own email
              client, your own WhatsApp, or an external profile. Nothing is captured on
              this domain when you click one.
            </p>
            <p>
              The site is hosted on a commercial hosting platform which, like all web
              hosts, records standard server request logs. These typically include your IP
              address, the page requested, a timestamp, the referring page and your
              browser user-agent string. These logs exist for security and reliability
              purposes, are generated by the hosting provider rather than by me, and are
              retained according to that provider&rsquo;s own retention schedule.
            </p>

            <h2>What I collect when you get in touch</h2>
            <p>
              If you email or message me, I receive whatever you choose to send: usually
              your name, email address, business name, website and a description of what
              you want. I use that information for one purpose only: to respond to your
              enquiry, run the free audit you asked for, and if we go on to work together,
              to deliver and invoice for that work.
            </p>
            <p>
              I do not sell contact details, rent mailing lists, or add anybody to a
              marketing list without an explicit request. If you enquire and we do not end
              up working together, you will not receive follow-up marketing from me.
            </p>

            <h2>Client account access</h2>
            <p>
              Delivering local search work usually requires access to systems you own:
              your Google Business Profile, Google Search Console, Google Analytics and
              sometimes your website&rsquo;s admin area. Access is always requested as a
              delegated user on your own account rather than by taking your password, so
              that you can see exactly what level of access has been granted and revoke it
              yourself at any time, without involving me.
            </p>
            <p>
              I will never ask you to send a password, a two-factor code or a recovery
              code by email or message. Any message claiming to be from me that asks for
              those is not from me. Account access is removed at the end of an engagement,
              and you can revoke it sooner at any point.
            </p>

            <h2>Performance data and case studies</h2>
            <p>
              Screenshots of client performance data are published on this site only with
              that client&rsquo;s permission. Where permission has been given but the
              business prefers not to be identified, the account name is removed and only
              the business category and market are shown. Client names in testimonials are
              published with the named person&rsquo;s consent, and any client can ask to
              have their data, screenshots or testimonial removed at any time, for any
              reason, without explanation.
            </p>

            <h2>Who your data is shared with</h2>
            <p>
              No third-party marketing or data brokers, ever. The only processors involved
              are the ordinary ones needed to run a consultancy: the website host, the
              email provider that carries our correspondence, and the payment processor
              that handles invoices. Each holds only what it needs for that function.
            </p>

            <h2>How long it is kept</h2>
            <p>
              Enquiries that do not become engagements are deleted within twelve months.
              Client correspondence and delivery records are kept for the duration of the
              engagement and then for the period required for tax and accounting purposes,
              after which they are deleted.
            </p>

            <h2>Your rights</h2>
            <p>
              You can ask for a copy of what I hold about you, ask for it to be corrected,
              or ask for it to be deleted. Email{" "}
              <a href={`mailto:${site.email}`}>{site.email}</a> and I will action it
              within thirty days, normally much sooner. You do not need to give a reason,
              and there is no charge.
            </p>

            <h2>Changes to this policy</h2>
            <p>
              If this policy changes materially, the updated date at the top of the page
              will change with it. Existing clients will be told directly rather than
              being expected to re-read the page.
            </p>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
